#####################################################################
# TAG_TTC_01 [Verify the title of the page is tic-tac-toe]
#####################################################################
TAG_TTC_01:
  SHOULD BE EQUAL:
    Title :   tic-tac-toe
#####################################################################

#####################################################################
# TAG_TTC_02 [Verify the default values of boxes]
#####################################################################
TAG_TTC_02:
  SHOULD BE EQUAL:
    0-0 : ''
    0-1 : ''  
    0-2 : ''
    1-0 : ''
    1-1 : ''
    1-2 : ''
    2-0 : ''
    2-1 : ''
    2-2 : ''
#####################################################################

#####################################################################
# TAG_TTC_03 [Verify the default message for fresh login]
#####################################################################
TAG_TTC_03:
  SHOULD BE EQUAL: 
    Status:  Click to start
#####################################################################

#####################################################################
# TAG_TTC_04 [Verify the boxes records "O" the odd click]
#####################################################################
TAG_TTC_04:
  SHOULD BE EQUAL: 
    0-0:  O
#####################################################################

#####################################################################
# TAG_TTC_05 [Verify the boxes records "X" the even click]
#####################################################################
TAG_TTC_05:
  SHOULD BE EQUAL: 
    0-1:  X
#####################################################################

#####################################################################
# TAG_TTC_06 [Verify the boxes doesn't record click on already set element]
#####################################################################
TAG_TTC_06:
  SHOULD BE EQUAL: 
    0-1:  X
####################################################################

#####################################################################
# TAG_TTC_07 [Verify the status shows turn "X" after odd click]
#####################################################################
TAG_TTC_07:
  SHOULD BE EQUAL: 
    Status:   "TURN: X" 
#####################################################################

#####################################################################
# TAG_TTC_08 [Verify the status shows turn "O" after odd click]
#####################################################################
TAG_TTC_08:
  SHOULD BE EQUAL: 
    Status:   "TURN: O" 
#####################################################################

#####################################################################
# TAG_TTC_09 [Verify the status shows WON "O" after if "O" wins]
#####################################################################
TAG_TTC_09:
  SHOULD BE EQUAL: 
    Status:   "WON: O" 
#####################################################################     

#####################################################################
# TAG_TTC_10 [Verify the status shows WON "X" after if "X" wins]
#####################################################################
TAG_TTC_10:
  SHOULD BE EQUAL: 
    Status:   "WON: X"
#####################################################################


#####################################################################
# TAG_TTC_11 [Verify the Keys refresh screen after refresh]
#####################################################################
TAG_TTC_11:
  SHOULD BE EQUAL:
    0-0 : ''
    0-1 : ''  
    0-2 : ''
    1-0 : ''
    1-1 : ''
    1-2 : ''
    2-0 : ''
    2-1 : ''
    2-2 : ''
#####################################################################
